"""initial schema

Revision ID: 0001
Revises: 
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None


def upgrade() -> None:
    op.execute("create extension if not exists pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fetch_run',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fetcher', sa.Text(), nullable=False),
    sa.Column('ref', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('foods', sa.Integer(), server_default='0', nullable=False),
    sa.Column('observations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('layer', sa.Text(), nullable=False),
    sa.Column('licence', sa.Text(), nullable=False),
    sa.Column('gtin14', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('serving_text', sa.Text(), nullable=True),
    sa.Column('serving_g', sa.Numeric(), nullable=True),
    sa.Column('flags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('food_gtin14_idx', 'food', ['gtin14'], unique=False)
    op.create_index('food_name_trgm_idx', 'food', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('observation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('food_id', sa.Text(), nullable=False),
    sa.Column('nutrient', sa.Text(), nullable=False),
    sa.Column('value_per_100', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'nutrient', 'source', 'observed_at', name='observation_once')
    )
    op.create_index("observation_food_idx", "observation", ["food_id", "nutrient"])
    # The resolver: one served value per food and nutrient, best-trusted source first,
    # then the newest observation.
    # ponytail: fixed source ranks; a per-field trust table when brand uploads and label reads land.
    op.execute("""
        create view food_value as
        select distinct on (food_id, nutrient)
               food_id, nutrient, value_per_100, unit, source, observed_at
        from observation
        order by food_id, nutrient,
                 case source when 'brand' then 1 when 'label' then 2 when 'fdc' then 3 when 'off' then 4 else 9 end,
                 observed_at desc
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("drop view if exists food_value")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation')
    op.drop_index('food_name_trgm_idx', table_name='food', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('food_gtin14_idx', table_name='food')
    op.drop_table('food')
    op.drop_table('fetch_run')
    # ### end Alembic commands ###
